package com.example.september24.domain.models
import java.util.Date

data class Reminder(
    val id: Long = 0, // This can be generated by the data layer,
    val title: String,
    val date: Date,
    val time: String,
    val location: Location? = null
)