name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '17'  # Adjust based on your project requirements
        distribution: 'temurin'  # or 'zulu', depending on your preference
        
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with Gradle
      run: ./gradlew test

      
   # - name: Upload APK
  #    uses: actions/upload-artifact@v3
  #    with:
  #      name: app-debug.apk
   #     path: app/build/outputs/apk/debug/app-debug.apk
